name: Docker Image CI

on:
  push:
    branches:
      - "release/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: ["test", "stage", "production"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_IMAGE_NAME }}
          tags: |
            type=ref,event=branch,pattern=release-v(.*)
          flavor: |
            suffix=-${{ matrix.mode }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            MODE=${{ matrix.mode }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
